global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nakamoto-gl0'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'nakamoto-node-0:9000'
          - 'nakamoto-node-1:9010'
          - 'nakamoto-node-2:9020'
          - 'nakamoto-node-3:9030'
          - 'nakamoto-node-4:9040'
          - 'nakamoto-node-5:9050'
          - 'nakamoto-node-6:9060'
          - 'nakamoto-node-7:9070'
        labels:
          layer: 'gl0'

  - job_name: 'nakamoto-l1'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'nakamoto-l1-0:9100'
          - 'nakamoto-l1-1:9110'
          - 'nakamoto-l1-2:9120'
        labels:
          layer: 'dag-l1'
