// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: sidecar.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarService_PublishSnapshot_FullMethodName    = "/nakamoto.p2p.SidecarService/PublishSnapshot"
	SidecarService_PublishAttestation_FullMethodName = "/nakamoto.p2p.SidecarService/PublishAttestation"
	SidecarService_PublishRumor_FullMethodName       = "/nakamoto.p2p.SidecarService/PublishRumor"
	SidecarService_Subscribe_FullMethodName          = "/nakamoto.p2p.SidecarService/Subscribe"
	SidecarService_PeerCount_FullMethodName          = "/nakamoto.p2p.SidecarService/PeerCount"
	SidecarService_Health_FullMethodName             = "/nakamoto.p2p.SidecarService/Health"
)

// SidecarServiceClient is the client API for SidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The sidecar exposes this service on localhost for the JVM to call.
type SidecarServiceClient interface {
	// Publish a snapshot to the network (JVM won a slot).
	PublishSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish an attestation to the network.
	PublishAttestation(ctx context.Context, in *TipAttestation, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a generic rumor (event / BFT consensus message / etc).
	PublishRumor(ctx context.Context, in *Rumor, opts ...grpc.CallOption) (*PublishResponse, error)
	// Subscribe to incoming messages from the network.
	// Server-streaming: sidecar pushes received gossip to JVM.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipMessage], error)
	// Get connected peer count.
	PeerCount(ctx context.Context, in *PeerCountRequest, opts ...grpc.CallOption) (*PeerCountResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type sidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarServiceClient(cc grpc.ClientConnInterface) SidecarServiceClient {
	return &sidecarServiceClient{cc}
}

func (c *sidecarServiceClient) PublishSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishAttestation(ctx context.Context, in *TipAttestation, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishRumor(ctx context.Context, in *Rumor, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishRumor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SidecarService_ServiceDesc.Streams[0], SidecarService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, GossipMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_SubscribeClient = grpc.ServerStreamingClient[GossipMessage]

func (c *sidecarServiceClient) PeerCount(ctx context.Context, in *PeerCountRequest, opts ...grpc.CallOption) (*PeerCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerCountResponse)
	err := c.cc.Invoke(ctx, SidecarService_PeerCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SidecarService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarServiceServer is the server API for SidecarService service.
// All implementations must embed UnimplementedSidecarServiceServer
// for forward compatibility.
//
// The sidecar exposes this service on localhost for the JVM to call.
type SidecarServiceServer interface {
	// Publish a snapshot to the network (JVM won a slot).
	PublishSnapshot(context.Context, *Snapshot) (*PublishResponse, error)
	// Publish an attestation to the network.
	PublishAttestation(context.Context, *TipAttestation) (*PublishResponse, error)
	// Publish a generic rumor (event / BFT consensus message / etc).
	PublishRumor(context.Context, *Rumor) (*PublishResponse, error)
	// Subscribe to incoming messages from the network.
	// Server-streaming: sidecar pushes received gossip to JVM.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[GossipMessage]) error
	// Get connected peer count.
	PeerCount(context.Context, *PeerCountRequest) (*PeerCountResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSidecarServiceServer()
}

// UnimplementedSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarServiceServer struct{}

func (UnimplementedSidecarServiceServer) PublishSnapshot(context.Context, *Snapshot) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSnapshot not implemented")
}
func (UnimplementedSidecarServiceServer) PublishAttestation(context.Context, *TipAttestation) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAttestation not implemented")
}
func (UnimplementedSidecarServiceServer) PublishRumor(context.Context, *Rumor) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishRumor not implemented")
}
func (UnimplementedSidecarServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[GossipMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSidecarServiceServer) PeerCount(context.Context, *PeerCountRequest) (*PeerCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeerCount not implemented")
}
func (UnimplementedSidecarServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSidecarServiceServer) mustEmbedUnimplementedSidecarServiceServer() {}
func (UnimplementedSidecarServiceServer) testEmbeddedByValue()                        {}

// UnsafeSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarServiceServer will
// result in compilation errors.
type UnsafeSidecarServiceServer interface {
	mustEmbedUnimplementedSidecarServiceServer()
}

func RegisterSidecarServiceServer(s grpc.ServiceRegistrar, srv SidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarService_ServiceDesc, srv)
}

func _SidecarService_PublishSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TipAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishAttestation(ctx, req.(*TipAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishRumor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rumor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishRumor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishRumor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishRumor(ctx, req.(*Rumor))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SidecarServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, GossipMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_SubscribeServer = grpc.ServerStreamingServer[GossipMessage]

func _SidecarService_PeerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PeerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PeerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PeerCount(ctx, req.(*PeerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarService_ServiceDesc is the grpc.ServiceDesc for SidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nakamoto.p2p.SidecarService",
	HandlerType: (*SidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishSnapshot",
			Handler:    _SidecarService_PublishSnapshot_Handler,
		},
		{
			MethodName: "PublishAttestation",
			Handler:    _SidecarService_PublishAttestation_Handler,
		},
		{
			MethodName: "PublishRumor",
			Handler:    _SidecarService_PublishRumor_Handler,
		},
		{
			MethodName: "PeerCount",
			Handler:    _SidecarService_PeerCount_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SidecarService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SidecarService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sidecar.proto",
}
