// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: sidecar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A snapshot produced by a slot winner, broadcast via GossipSub.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                       // 32 bytes, snapshot hash
	Slot          int64                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`                                      // slot number
	Ordinal       int64                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`                                // snapshot ordinal
	ParentHash    []byte                 `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`         // 32 bytes, parent snapshot hash
	VrfProof      []byte                 `protobuf:"bytes,5,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`               // 80 bytes, VRF proof (Gamma || c || s)
	VrfPublicKey  []byte                 `protobuf:"bytes,6,opt,name=vrf_public_key,json=vrfPublicKey,proto3" json:"vrf_public_key,omitempty"` // 32 bytes, Ed25519 VRF public key
	Eta           []byte                 `protobuf:"bytes,7,opt,name=eta,proto3" json:"eta,omitempty"`                                         // 32 bytes, epoch randomness
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`                                 // serialized snapshot body (opaque to sidecar)
	ProducerId    []byte                 `protobuf:"bytes,9,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`         // peer identity of the producer
	ParentSlot    int64                  `protobuf:"varint,10,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`       // slot of parent snapshot (for slot gap verification)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Snapshot) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Snapshot) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Snapshot) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Snapshot) GetVrfProof() []byte {
	if x != nil {
		return x.VrfProof
	}
	return nil
}

func (x *Snapshot) GetVrfPublicKey() []byte {
	if x != nil {
		return x.VrfPublicKey
	}
	return nil
}

func (x *Snapshot) GetEta() []byte {
	if x != nil {
		return x.Eta
	}
	return nil
}

func (x *Snapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Snapshot) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *Snapshot) GetParentSlot() int64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

// A validator's endorsement of a chain tip.
type TipAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipHash       []byte                 `protobuf:"bytes,1,opt,name=tip_hash,json=tipHash,proto3" json:"tip_hash,omitempty"`           // 32 bytes, hash of endorsed snapshot
	TipSlot       int64                  `protobuf:"varint,2,opt,name=tip_slot,json=tipSlot,proto3" json:"tip_slot,omitempty"`          // slot of that snapshot
	TipOrdinal    int64                  `protobuf:"varint,3,opt,name=tip_ordinal,json=tipOrdinal,proto3" json:"tip_ordinal,omitempty"` // ordinal of that snapshot
	AttestedAt    int64                  `protobuf:"varint,4,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"` // slot when attestation was created
	AttesterId    []byte                 `protobuf:"bytes,5,opt,name=attester_id,json=attesterId,proto3" json:"attester_id,omitempty"`  // peer identity of the attester
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                      // signature over (tip_hash || tip_slot)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TipAttestation) Reset() {
	*x = TipAttestation{}
	mi := &file_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TipAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipAttestation) ProtoMessage() {}

func (x *TipAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipAttestation.ProtoReflect.Descriptor instead.
func (*TipAttestation) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *TipAttestation) GetTipHash() []byte {
	if x != nil {
		return x.TipHash
	}
	return nil
}

func (x *TipAttestation) GetTipSlot() int64 {
	if x != nil {
		return x.TipSlot
	}
	return 0
}

func (x *TipAttestation) GetTipOrdinal() int64 {
	if x != nil {
		return x.TipOrdinal
	}
	return 0
}

func (x *TipAttestation) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

func (x *TipAttestation) GetAttesterId() []byte {
	if x != nil {
		return x.AttesterId
	}
	return nil
}

func (x *TipAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A generic signed rumor — used to carry events, BFT consensus messages,
// and other Tessellation gossip payloads on top of GossipSub. The sidecar
// treats the body as opaque bytes; the JVM is responsible for serialization,
// signing, and validation.
type Rumor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed rumor envelope, JSON-serialized by the JVM and wrapped in the
	// standard Tessellation `Signed[RumorRaw]` shape. Opaque to the sidecar.
	SignedRumorBytes []byte `protobuf:"bytes,1,opt,name=signed_rumor_bytes,json=signedRumorBytes,proto3" json:"signed_rumor_bytes,omitempty"`
	// Content type discriminator (e.g. "io.constellationnetwork...Event").
	// Carried alongside the bytes for cheap routing/metrics on the sidecar.
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Origin peer id (for logging/dedup hints — authoritative origin is in the
	// signed envelope).
	OriginId      []byte `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rumor) Reset() {
	*x = Rumor{}
	mi := &file_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rumor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rumor) ProtoMessage() {}

func (x *Rumor) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rumor.ProtoReflect.Descriptor instead.
func (*Rumor) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *Rumor) GetSignedRumorBytes() []byte {
	if x != nil {
		return x.SignedRumorBytes
	}
	return nil
}

func (x *Rumor) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Rumor) GetOriginId() []byte {
	if x != nil {
		return x.OriginId
	}
	return nil
}

// Envelope for GossipSub messages.
type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*GossipMessage_Snapshot
	//	*GossipMessage_Attestation
	//	*GossipMessage_Rumor
	Body          isGossipMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *GossipMessage) GetBody() isGossipMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GossipMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *GossipMessage) GetAttestation() *TipAttestation {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Attestation); ok {
			return x.Attestation
		}
	}
	return nil
}

func (x *GossipMessage) GetRumor() *Rumor {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Rumor); ok {
			return x.Rumor
		}
	}
	return nil
}

type isGossipMessage_Body interface {
	isGossipMessage_Body()
}

type GossipMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type GossipMessage_Attestation struct {
	Attestation *TipAttestation `protobuf:"bytes,2,opt,name=attestation,proto3,oneof"`
}

type GossipMessage_Rumor struct {
	Rumor *Rumor `protobuf:"bytes,3,opt,name=rumor,proto3,oneof"`
}

func (*GossipMessage_Snapshot) isGossipMessage_Body() {}

func (*GossipMessage_Attestation) isGossipMessage_Body() {}

func (*GossipMessage_Rumor) isGossipMessage_Body() {}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *PublishResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which message types to receive. Empty = all.
	Topics        []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type PeerCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCountRequest) Reset() {
	*x = PeerCountRequest{}
	mi := &file_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountRequest) ProtoMessage() {}

func (x *PeerCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountRequest.ProtoReflect.Descriptor instead.
func (*PeerCountRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{6}
}

type PeerCountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Total            int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MeshSnapshots    int32                  `protobuf:"varint,2,opt,name=mesh_snapshots,json=meshSnapshots,proto3" json:"mesh_snapshots,omitempty"`          // peers in snapshot topic mesh
	MeshAttestations int32                  `protobuf:"varint,3,opt,name=mesh_attestations,json=meshAttestations,proto3" json:"mesh_attestations,omitempty"` // peers in attestation topic mesh
	MeshRumors       int32                  `protobuf:"varint,4,opt,name=mesh_rumors,json=meshRumors,proto3" json:"mesh_rumors,omitempty"`                   // peers in rumor topic mesh
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerCountResponse) Reset() {
	*x = PeerCountResponse{}
	mi := &file_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountResponse) ProtoMessage() {}

func (x *PeerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountResponse.ProtoReflect.Descriptor instead.
func (*PeerCountResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *PeerCountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PeerCountResponse) GetMeshSnapshots() int32 {
	if x != nil {
		return x.MeshSnapshots
	}
	return 0
}

func (x *PeerCountResponse) GetMeshAttestations() int32 {
	if x != nil {
		return x.MeshAttestations
	}
	return 0
}

func (x *PeerCountResponse) GetMeshRumors() int32 {
	if x != nil {
		return x.MeshRumors
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PeerCount     int32                  `protobuf:"varint,3,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\fnakamoto.p2p\"\x9e\x02\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x03R\x04slot\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x03R\aordinal\x12\x1f\n" +
	"\vparent_hash\x18\x04 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tvrf_proof\x18\x05 \x01(\fR\bvrfProof\x12$\n" +
	"\x0evrf_public_key\x18\x06 \x01(\fR\fvrfPublicKey\x12\x10\n" +
	"\x03eta\x18\a \x01(\fR\x03eta\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1f\n" +
	"\vproducer_id\x18\t \x01(\fR\n" +
	"producerId\x12\x1f\n" +
	"\vparent_slot\x18\n" +
	" \x01(\x03R\n" +
	"parentSlot\"\xc7\x01\n" +
	"\x0eTipAttestation\x12\x19\n" +
	"\btip_hash\x18\x01 \x01(\fR\atipHash\x12\x19\n" +
	"\btip_slot\x18\x02 \x01(\x03R\atipSlot\x12\x1f\n" +
	"\vtip_ordinal\x18\x03 \x01(\x03R\n" +
	"tipOrdinal\x12\x1f\n" +
	"\vattested_at\x18\x04 \x01(\x03R\n" +
	"attestedAt\x12\x1f\n" +
	"\vattester_id\x18\x05 \x01(\fR\n" +
	"attesterId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"u\n" +
	"\x05Rumor\x12,\n" +
	"\x12signed_rumor_bytes\x18\x01 \x01(\fR\x10signedRumorBytes\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\torigin_id\x18\x03 \x01(\fR\boriginId\"\xbc\x01\n" +
	"\rGossipMessage\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.nakamoto.p2p.SnapshotH\x00R\bsnapshot\x12@\n" +
	"\vattestation\x18\x02 \x01(\v2\x1c.nakamoto.p2p.TipAttestationH\x00R\vattestation\x12+\n" +
	"\x05rumor\x18\x03 \x01(\v2\x13.nakamoto.p2p.RumorH\x00R\x05rumorB\x06\n" +
	"\x04body\"7\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x12\n" +
	"\x10PeerCountRequest\"\x9e\x01\n" +
	"\x11PeerCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12%\n" +
	"\x0emesh_snapshots\x18\x02 \x01(\x05R\rmeshSnapshots\x12+\n" +
	"\x11mesh_attestations\x18\x03 \x01(\x05R\x10meshAttestations\x12\x1f\n" +
	"\vmesh_rumors\x18\x04 \x01(\x05R\n" +
	"meshRumors\"\x0f\n" +
	"\rHealthRequest\"p\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x03 \x01(\x05R\tpeerCount2\xd0\x03\n" +
	"\x0eSidecarService\x12H\n" +
	"\x0fPublishSnapshot\x12\x16.nakamoto.p2p.Snapshot\x1a\x1d.nakamoto.p2p.PublishResponse\x12Q\n" +
	"\x12PublishAttestation\x12\x1c.nakamoto.p2p.TipAttestation\x1a\x1d.nakamoto.p2p.PublishResponse\x12B\n" +
	"\fPublishRumor\x12\x13.nakamoto.p2p.Rumor\x1a\x1d.nakamoto.p2p.PublishResponse\x12J\n" +
	"\tSubscribe\x12\x1e.nakamoto.p2p.SubscribeRequest\x1a\x1b.nakamoto.p2p.GossipMessage0\x01\x12L\n" +
	"\tPeerCount\x12\x1e.nakamoto.p2p.PeerCountRequest\x1a\x1f.nakamoto.p2p.PeerCountResponse\x12C\n" +
	"\x06Health\x12\x1b.nakamoto.p2p.HealthRequest\x1a\x1c.nakamoto.p2p.HealthResponseB-Z+github.com/scasplte2/tessellation/p2p/protob\x06proto3"

var (
	file_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_proto_rawDescData []byte
)

func file_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)))
	})
	return file_sidecar_proto_rawDescData
}

var file_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sidecar_proto_goTypes = []any{
	(*Snapshot)(nil),          // 0: nakamoto.p2p.Snapshot
	(*TipAttestation)(nil),    // 1: nakamoto.p2p.TipAttestation
	(*Rumor)(nil),             // 2: nakamoto.p2p.Rumor
	(*GossipMessage)(nil),     // 3: nakamoto.p2p.GossipMessage
	(*PublishResponse)(nil),   // 4: nakamoto.p2p.PublishResponse
	(*SubscribeRequest)(nil),  // 5: nakamoto.p2p.SubscribeRequest
	(*PeerCountRequest)(nil),  // 6: nakamoto.p2p.PeerCountRequest
	(*PeerCountResponse)(nil), // 7: nakamoto.p2p.PeerCountResponse
	(*HealthRequest)(nil),     // 8: nakamoto.p2p.HealthRequest
	(*HealthResponse)(nil),    // 9: nakamoto.p2p.HealthResponse
}
var file_sidecar_proto_depIdxs = []int32{
	0, // 0: nakamoto.p2p.GossipMessage.snapshot:type_name -> nakamoto.p2p.Snapshot
	1, // 1: nakamoto.p2p.GossipMessage.attestation:type_name -> nakamoto.p2p.TipAttestation
	2, // 2: nakamoto.p2p.GossipMessage.rumor:type_name -> nakamoto.p2p.Rumor
	0, // 3: nakamoto.p2p.SidecarService.PublishSnapshot:input_type -> nakamoto.p2p.Snapshot
	1, // 4: nakamoto.p2p.SidecarService.PublishAttestation:input_type -> nakamoto.p2p.TipAttestation
	2, // 5: nakamoto.p2p.SidecarService.PublishRumor:input_type -> nakamoto.p2p.Rumor
	5, // 6: nakamoto.p2p.SidecarService.Subscribe:input_type -> nakamoto.p2p.SubscribeRequest
	6, // 7: nakamoto.p2p.SidecarService.PeerCount:input_type -> nakamoto.p2p.PeerCountRequest
	8, // 8: nakamoto.p2p.SidecarService.Health:input_type -> nakamoto.p2p.HealthRequest
	4, // 9: nakamoto.p2p.SidecarService.PublishSnapshot:output_type -> nakamoto.p2p.PublishResponse
	4, // 10: nakamoto.p2p.SidecarService.PublishAttestation:output_type -> nakamoto.p2p.PublishResponse
	4, // 11: nakamoto.p2p.SidecarService.PublishRumor:output_type -> nakamoto.p2p.PublishResponse
	3, // 12: nakamoto.p2p.SidecarService.Subscribe:output_type -> nakamoto.p2p.GossipMessage
	7, // 13: nakamoto.p2p.SidecarService.PeerCount:output_type -> nakamoto.p2p.PeerCountResponse
	9, // 14: nakamoto.p2p.SidecarService.Health:output_type -> nakamoto.p2p.HealthResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	file_sidecar_proto_msgTypes[3].OneofWrappers = []any{
		(*GossipMessage_Snapshot)(nil),
		(*GossipMessage_Attestation)(nil),
		(*GossipMessage_Rumor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
		MessageInfos:      file_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
